# Official Ruby 3.4.11 on Alpine 3.23; no package installation or project build context.
ARG EMPEIRA_BASE_RUBY=library/ruby:3.4.11-alpine3.23
FROM ${EMPEIRA_BASE_RUBY}
USER 65534:65534
ENTRYPOINT ["ruby"]
